plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.suitexen.opencv'
    compileSdk 36

    defaultConfig {
        applicationId "com.suitexen.opencv"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        // ★ শুধু ARM ABI — x86 বাদ দাও (error এর কারণ)
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        externalNativeBuild {
            cmake {
                arguments "-DCMAKE_SHARED_LINKER_FLAGS=-Wl,-z,max-page-size=16384", "-DCMAKE_CXX_FLAGS=-O2 -fvisibility=hidden"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    // ★ এখানে correct relative path
    externalNativeBuild {
        cmake {
            path "../sdk/libcxx_helper/CMakeLists.txt"
            version "3.22.1+"
        }
    }
    packaging {
        jniLibs {
            useLegacyPackaging = false
            excludes.add('**/lib/**/x86/**')
            excludes.add('**/lib/**/x86_64/**')


        }
        resources {
            excludes.add('**/lib/**/x86/**')
            excludes.add('**/lib/**/x86_64/**')
        }
    }
}

dependencies {
    implementation project(':sdk')
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit

    // ★ আপডেটেড TFLite (২.১৬.১ - এতে ১৬KB অ্যালাইনমেন্ট বিল্ট-ইন আছে)
    implementation 'org.tensorflow:tensorflow-lite:2.16.1'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.16.1'
    implementation 'org.tensorflow:tensorflow-lite-gpu-api:2.16.1'
    implementation 'org.tensorflow:tensorflow-lite-support:0.4.4'
}
